apiVersion: apps/v1
kind: Deployment
metadata:
  name: velsec-frontend
  labels:
    app: velsec-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: velsec-frontend
  template:
    metadata:
      labels:
        app: velsec-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/velsec-org/velsec-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: velsec-frontend-svc
spec:
  selector:
    app: velsec-frontend
  ports:
  - port: 80
    targetPort: 3000
